[package]
name = "old_dep"
version = "0.1.0"
authors = ["Paul Sanford <me@paulsanford.net>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
